### ISSUE TITLE
Occassional SQLite3 ProgrammingError

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/flux#4]
```
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840
Exception closing connection <sqlite3.Connection object at 0x10b66c8f0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840
Exception closing connection <sqlite3.Connection object at 0x10bc8de30>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 420, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4491997184 and this is thread id 140735296131840
```

I have no idea where it comes from.

**Comment by NiklasRosenstein** [comment]
Using `sqlalchemy.orm.scoped_session` doesn't fix it. It always appears the when the application is stopped.

**Comment by NiklasRosenstein** [comment]
I figured to sources of this error:

1. Not calling either of `session.rollback()` or `session.commit()`
2. Flask/Werkzeug debug reload

I don't have an idea how to solve the 2nd one.

**Comment by NiklasRosenstein** [comment]
I think the second is from the fact that there are actually two independent builder threads created due to the Werkzeug reloader.

```
 * starting builder threads...
 * Restarting with stat
 * starting builder threads...
 * Debugger is active!
 * Debugger pin code: 124-669-299
```

**Comment by NiklasRosenstein** [comment]
Fixed as long as we don't use the Werkzeug reloader.
